# Generated by Django 3.1.2 on 2021-06-27 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateTimeField()),
                ('fechaFinReplanificada', models.DateTimeField()),
                ('fechaIncio', models.DateTimeField()),
                ('fechaInicioReplanificada', models.DateTimeField()),
                ('horaApertura', models.TimeField()),
                ('horaCierre', models.TimeField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaApertura', models.TimeField()),
                ('horaCierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('codigoSensor', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('duracionExtendida', models.FloatField()),
                ('duracionResumida', models.FloatField()),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaPrimerIngreso', models.DateTimeField()),
                ('nombreObra', models.CharField(max_length=20)),
                ('peso', models.FloatField()),
                ('valuacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantMaximaVisitantes', models.IntegerField()),
                ('cantMaxPorGuia', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFinVigencia', models.DateTimeField()),
                ('fechaInicioVigencia', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('montoAdicionalGuia', models.FloatField()),
                ('tipoEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoentrada')),
                ('tipoVisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipovisita')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('fechaVenta', models.DateTimeField()),
                ('horaVenta', models.TimeField()),
                ('monto', models.FloatField()),
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('codigoValidacion', models.CharField(max_length=20)),
                ('cuit', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=80)),
                ('fechaIngreso', models.DateTimeField()),
                ('fechaNacimiento', models.DateTimeField()),
                ('mail', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sedes', to='app.sede')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleExposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarAsignado', models.CharField(max_length=20)),
                ('exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exposicion')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra')),
            ],
        ),
    ]
