# Generated by Django 3.1.2 on 2021-06-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposicion',
            old_name='fechaIncio',
            new_name='fechaInicio',
        ),
    ]
