# Generated by Django 3.1.2 on 2021-06-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='exposicion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='exposicion', to='app.exposicion'),
            preserve_default=False,
        ),
    ]
