# Generated by Django 3.1.2 on 2021-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210629_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoentrada',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tipovisita',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
