# Generated by Django 3.1.2 on 2021-06-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sede_exposicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicion',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.sede'),
            preserve_default=False,
        ),
    ]
