# Generated by Django 3.1.2 on 2021-06-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210627_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicion',
            name='sede',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expos', to='app.sede'),
        ),
    ]
