# Generated by Django 3.1.2 on 2021-06-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210627_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorRegistrarVentaEntradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadEntradas', models.IntegerField()),
                ('cantMaximaVisitantes', models.IntegerField()),
                ('cantVisitantesActuales', models.IntegerField()),
                ('ultimoNroEntrada', models.IntegerField()),
            ],
        ),
    ]
