# Generated by Django 3.1.2 on 2021-06-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gestorregistrarventaentradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantAlumnos', models.IntegerField()),
                ('cantAlumnosConfirmada', models.IntegerField()),
                ('duracionEstimada', models.IntegerField()),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraReserva', models.DateTimeField()),
                ('horaFinReal', models.TimeField()),
                ('horaInicioReal', models.TimeField()),
                ('numeroReserva', models.IntegerField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede')),
            ],
        ),
    ]
