# Generated by Django 3.1.2 on 2021-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservavisita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fechaVenta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
