# Generated by Django 3.1.2 on 2021-06-29 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210629_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'get_latest_by': ['numero']},
        ),
    ]
